name: ChatWithStaff
description: Chat with your staff in private.
author: Jessible
website: https://www.spigotmc.org/resources/25182
version: 1.0.3.0
main: com.jessible.chatwithstaff.ChatWithStaff
commands:
  chatwithstaff:
    description: View plugin information about ChatWithStaff.
    aliases: [cws]
  staffchat:
    description: Send a message to all staff members or toggle staff chat mode.
    aliases: [sc]
  staffchatlist:
    description: Show all staff members viewing staff chat.
    aliases: [scl]